site_name: Ad-Omnia
site_description: Projeto em Engenharia Informática 2026/2027 - Universidade de Aveiro
site_url: https://ad-omnia.github.io/micro-site/
repo_url: https://github.com/Ad-Omnia/micro-site
repo_name: Ad-Omnia/micro-site

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: pt
  favicon: assets/logo-colour-black.png
  custom_dir: overrides
  logo: assets/logo-colour-black.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - content.code.copy
  font:
    text: Calibri
    code: Roboto Mono
  palette:
    - scheme: default
      primary: white
      accent: green
      toggle:
        icon: material/weather-night
        name: Modo escuro
    - scheme: slate
      primary: white
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Modo claro

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Ir descomentando/expandindo à medida que as páginas forem criadas
nav:
  - Documentation: documentation.md
  - Journey: calendar-general.md
  - Milestones:
      - MS1 - Fase de Inception:
          - Descrição do projeto: milestones/ms1-inception/descricao-projeto.md
          - Calendário do projeto: milestones/ms1-inception/calendario.md
          - Plano de comunicação: milestones/ms1-inception/plano-comunicacao.md
      - MS2 - Fase de Elaboration:
          - Em breve: milestones/ms2-elaboration/em-breve.md
      - MS3 - Fase de Construction:
          - Em breve: milestones/ms3-construction/em-breve.md
      - MS4 - Fase de Transition:
          - Em breve: milestones/ms4-transition/em-breve.md
      - Calendário geral: milestones/calendario-geral.md
  - Minutes
  - Team: team.md
  # - Arquitetura: arquitetura.md
  # - Relatórios e apresentações: relatorios.md

copyright: "© 2027 Ad-Omnia · Universidade de Aveiro"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ad-Omnia